name: CommunicationConnector
author: RoboMWM
version: ${project.version}
main: to.us.mlgfort.communicationconnector.CommunicationConnector
depend: [PurpleIRC]
softdepend:
  - SlackIntegration
commands:
  communicationconnector: {}
